TooAngel/screeps

FAQ.md
README.md
src/config.js
src/config_brain_squadmanager.js
src/main.js
src/prototype_creep.js
src/prototype_creep_clean.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_creep_startup_tasks.js
src/prototype_room_basebuilder.js
src/prototype_room_controller.js
src/prototype_room_memory.js
src/prototype_room_my.js
src/prototype_room_wallsetter.js
src/role_nextroomer.js
src/role_planer.js
src/role_scoutnextroom.js
src/role_upgrader.js
src/util.js

To be enable other players to get of the "Don't like" list, or
idiot counter. Resources can be transfered and based on the market
price of the resource the idiot counter will be reduced.

Incoming transaction will reduce the idiot counter

---

.gitignore
README.md
config_local.js.example
src/.gitignore
src/config.js
src/config_local.js.example
src/prototype_creep_startup_tasks.js
src/require.js

Maybe this is better as you'll be merging in stuff anyways.

Stuff instead of master

---

Alliance.md
README.md

Added the Info about the alliance.
The Charter is a proposal with a request for comment.

Add alliance info

---

.jshintrc
src/config.js
src/prototype_creep_move.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_room_attack.js
src/prototype_room_my.js
src/prototype_structure.js
src/require.js
src/role_autoattackmelee.js

Better basic harvesters so only need 2-4 rather than 5 or more.

Fix harvester logic

---

.jshintrc
src/config.js
src/prototype_creep_move.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_room_attack.js
src/prototype_room_my.js
src/prototype_structure.js
src/require.js
src/role_autoattackmelee.js

Was https://github.com/TooAngel/screeps/pull/44

Re-land stuff branch PR

---

src/prototype_room_my.js

Some stats added plus rooms separated by players

Screepsplus & Grafana stats improve

---

src/prototype_creep_harvest.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/prototype_room_utils.js

Fix missing queue

---

src/require.js
src/utils.js

first part for #66 
i ll and some function here soon, so please wait a day or two before merging

introducing global.utils a function collection (part 1)

---

src/config.js
src/prototype_creep_resources.js

add config var for allow to skip pathfind again if path incomplete.

path incomplete modif Fixes #37

---

.gitignore
Gruntfile.js
README.md
account.screeps.com.js.sample
src/account.screeps.com.js.sample

> .gitignore
- idea
- steam sync file
- account.screeps.com.js - contains screeps.com login information

updated gitignore and added account.screeps.com.js.sample

---

src/prototype_creep_startup_tasks.js

Use Creep.moveRandomWithin(target) to keep the creep within range for
continual upgrading/repairing but also allow random movement.

Fix rampart and use moveRandomWithin

---

src/prototype_room_utils.js
src/role_nextroomer.js
src/role_scoutnextroom.js

Maybe this will help with duplicate repairers? Can't really see how
that happens. #46

Clean-up and better scoutnextroom info

---

Design.md
Gruntfile.js
README.md
src/prototype_creep_resources.js
src/prototype_room_external.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/role_scout.js
src/utils.js

Sourcer and server can queue up way too much, using checkRoleToSpawn prevents this.
Split out the AI desgin to a separate file.

README and checkRoleToSpawn for sourcer and reserver 

---

src/role_carry.js
src/role_sourcer.js

Fix for https://github.com/TooAngel/screeps/issues/84
Use 'target' instead of 'x/y' or 'pos'

Forced Reserver Sourcer & Carry Fix

---

src/prototype_creep_routing.js

Fixing this typo, maybe this will resolve it? Testing plz :)

Fix allowRoutingThroughFriendRooms resolves #34

---

src/prototype_creep_resources.js
src/prototype_room_my.js
src/role_nextroomer.js
src/role_storagefiller.js
src/role_towerfiller.js

- Rename `attack_timer` to `attackTimer`
- Initialize memory value on room execution

Initialize attackTimer

---

src/config.js
src/config_brain_nextroom.js
src/role_scoutnextroom.js

Improve scoutnextroom.

---

src/role_carry.js

This change can be introduced here too to resolve #125 ?

hotfix/carry-range-check #125

---

src/role_sourcer.js

as above, does this work,and does this affect anything else? #108 ?

hotfix/Fix sourcer range check when misplaced spawn #108

---

src/role_carry.js

Revert "hotfix/carry-range-check #125"

---

src/role_sourcer.js

Fixes "hotfix/sourcer-path-when-missplacedSpawn #124"

---

README.md
doc/Constribution-and-Workflow.md

Add constribution markdown and edit readme resolves #104

---

src/role_scout.js

This works, but maybe not the right way to fix it? Comments welcome.

Fix scout stuck issue

---

.jsbeautifyrc
src/config_brain_stats.js
src/main.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/prototype_room_routing.js
src/visualizer.js

Small fixes for the `stats.add(` method to be more generic.
Fix initializiation errors for enabling / disabling stats
and `delete Memory.stats`

Fix memory initialization errors and more general path

---

src/role_carry.js

fix the nonworking carrys at rcl < 3

---

src/role_carry.js
src/role_scout.js
src/role_sourcer.js

Fix sourcer with misplaced spawn

---

.gitignore
Gruntfile.js
README.md

Add a `.localSync.js` for local folder syncronization. Excluded via `.gitignore`.

Improve private server deploy

---

src/prototype_room_controller.js

This room reset was introduced as a bug on the private server.

Remove private server fix

---

src/prototype_creep.js
src/prototype_creep_fight.js
src/prototype_creep_mineral.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_creep_startup_tasks.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_defense.js
src/prototype_room_external.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/prototype_room_wallsetter.js
src/role_nextroomer.js
src/role_powerattacker.js
src/role_powerdefender.js
src/role_powerhealer.js
src/role_powertransporter.js

convert all existing find compatibles.

add findOnly/Without methods

---

src/prototype_room_creepbuilder.js

new creepMem & inRooms
add a room.memory.role for skip 10 next ticks roleSpawn if we don't need them

new checkRoleToSpawn simplified

---

src/role_nextroomer.js

This was obviously wrong. I believe this is the intended behaviour. Can you please confirm that?

Fix: crash in roles.nextroomer.died

---

src/config_brain_memory.js
src/config_brain_stats.js
src/main.js
src/prototype_room_creepbuilder.js

It should work but cherry pick it so must try before remove WIP.
I should do it quickly.
update: ready to merge

some stats changements

---

src/prototype_room_creepbuilder.js
src/prototype_room_defense.js
src/role_harvester.js
src/role_nextroomer.js
src/role_reserver.js

`jsbeautify` and fixing warnings in for `jscs`

Format fixes

---

src/config.js
src/prototype_creep_routing.js
src/prototype_room_my.js
src/prototype_room_routing.js

For nextroomers and helpers there could be no route to the target.
So check if a route is available.

Extract findRoute to room

---

.jshintrc
src/config.js
src/config_brain_stats.js
src/prototype_creep_fight.js
src/prototype_roomPosition.js
src/prototype_room_creepbuilder.js
src/prototype_room_routing.js
src/role_defender.js
src/role_harvester.js

Improve code quality, mainly by extracting and combining methods.

Fix spawning issue and codeClimate for prototype_creep_fight

---

src/config_brain_memory.js

previous solution causes an undef, see https://github.com/ScreepsOCS/screeps.behaviour-action-pattern/pull/956/files

don't crash when you lose all your spawns

---

src/config.js
src/config_brain_memory.js
src/config_brain_stats.js
src/prototype_creep.js
src/prototype_creep_harvest.js
src/prototype_room.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_init.js
src/prototype_room_memory.js
src/prototype_room_my.js
src/prototype_room_routing.js
src/prototype_room_wallsetter.js
src/role_scout.js

CostMatrixes are stored in plain format in the cache.
CostMatrixes of controlled rooms are stored in `Memory` serialized.

Introduce cache / memory methods for costMatrix

---

src/prototype_creep.js
src/prototype_creep_routing.js
src/prototype_room_external.js
src/prototype_room_routing.js
src/prototype_room_wallsetter.js

This can change the room layout

Set upgrader position before others

---

src/role_upgrader.js

This reverts commit fd33073a09fdfb9231d22b3ab3f22b5b1935d000.
Was testing the democrat collaboration bug and this one was accidentally merged.

Revert "Some builder issue"

---

src/main.js
src/prototype_creep.js
src/prototype_creep_move.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_creepbuilder.js
src/prototype_room_external.js
src/prototype_room_init.js
src/prototype_room_memory.js
src/prototype_room_my.js
src/prototype_room_routing.js
src/role_carry.js
src/role_harvester.js
src/role_sourcer.js

Build other positions only in my rooms
Improve buildCostMatrix
initSetStorageAndPathStart
buildCostMatrix simplify
Improve buildCostMatrix
Fix costmatrix issues
Remove debug output
Fix filler area
Small fixes to get it working
Remove debug output
Reset filler path, if the first position is not valid
Fix planer stuck?
Fix filler costmatrix issue

Move and simplify updatePosition

---

Gruntfile.js

Fixing a BUG when upload to screeps.com using account.screeps.com.js

Fixing upload to screeps.com BUG

---

src/role_scout.js

Noticed in tight spots he would get stuck in traffic, or between objects, this fixed him up a little

Update role_scout to unstick himself

---

src/prototype_creep_resources.js
src/prototype_room.js
src/prototype_room_controller.js
src/prototype_room_creepbuilder.js
src/prototype_room_defense.js
src/prototype_room_external.js
src/prototype_room_mineral.js
src/prototype_room_my.js

Extract method to check if a certain needs to be executed on this tick.
To make sure the execution of the same task in different rooms, the
position of the controller is used as offset to the current Game tick.

Room.executeEveryTick

---

src/config.js
src/prototype_creep.js
src/prototype_room_costmatrix.js
src/prototype_room_creepbuilder.js
src/prototype_room_init.js
src/prototype_room_my.js
src/role_extractor.js
src/role_nextroomer.js
src/role_sourcer.js
src/role_upgrader.js

Fix issue with same creep spawned multiple times
Fixes #239

Improve spawning logic

---

src/prototype_room_costmatrix.js
src/prototype_room_external.js
src/prototype_room_init.js
src/role_scout.js

Fix `setCostMatrixStructures` call error

---

src/role_nextroomer.js

Do not care about hostile creeps if safe mode is active (and will not end until all hostile creeps are die)

Do not care about hostile creeps if safe mode is active

---

.jshintrc
src/prototype_creep_move.js
src/prototype_roomPosition.js

Do not make useless moves into obstacle

Speed up traffic jams resolution based on random movement

---

src/prototype_creep.js

Do not kill previous creep with same role and different target

---

src/role_nextroomer.js

Upgrade controller if it was downgraded recently
Build spawn if no one exists yet (even on low RCL)

Improve prioritizing of nextroomer tasks

---

.jshintrc
src/config.js
src/prototype_room_costmatrix.js

Have no clue how this change will affect harvesting in sk rooms

Avoid source keeper lairs in cost matrix

---

Gruntfile.js
circle.yml
package.json
src/config.js

Let circleCI deploy the code to the tooangel screeps account.

Auto deploy on merge to master or workspace

---

src/config.js
src/main.js
src/prototype_creep.js
src/prototype_creep_move.js
src/prototype_creep_resources.js
src/prototype_room.js
src/prototype_roomPosition.js
src/prototype_room_basebuilder.js
src/prototype_room_controller.js
src/prototype_room_creepbuilder.js
src/prototype_room_defense.js
src/prototype_room_init.js
src/prototype_room_memory.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/role_carry.js
src/role_harvester.js
src/role_reserver.js
src/role_sourcer.js
src/role_upgrader.js

- Less constructionSites in parallel
- Reserver signs the controller
- Spawn sourcer earlier RCL 2
- Some getSettings fixes
- Make tower healing configurable
- Fix some creep_resources codeclimate issues
- Replace transferEnergy with withdraw
- Fix issue with cache initialization
Fixes #86

Small fixes testing on a private server

---

src/config.js
src/prototype_creep.js

Add option if we want to build roads to other owned rooms. Typically we may do that only on room needs energy event

Add option if we want to build roads to other owned rooms. 

---

README.md
circle.yml
package.json

Add automatic npm publish on version increase.

Npm publish

---

src/config.js
src/prototype_room_memory.js

do not sure if recalcing a needed at all

save all rooms' costmatrixes into memory on early game stages

---

src/prototype_creep.js
src/prototype_creep_fight.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js

- fix range parameter
- do not use in move to source, as moveToMy ignores creeps, so it is impossible for several creeps to harvest

fix moveToMy issues

---

src/prototype_creep.js

- fix regression: roads not build-up in external rooms
- build roads on swamps even at low RCL

improve buildRoad

---

src/config.js
src/prototype_creep_move.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_roomPosition.js
src/prototype_roomPosition_structures.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_init.js
src/role_harvester.js

- Refactor `setTowerFiller`
- Refactor `setLabsTerminal`
- Refactor `setStructures`
- Refactor `setup`
- Refactor `sorter`
- Replace `RoomPosition.isExit` with more generic `isBorder(offset)`
- Remove duplicates of setPosition in costmatrix and memory
- Fix structure setting
- Increase layout version
- Remove buildStructures debug output
- Fix transfer to storage

Refactor `prototype_room_init`

---

src/config.js
src/prototype_creep_resources.js
src/prototype_roomPosition.js
src/prototype_room_init.js
src/prototype_room_utils.js
src/role_sourcer.js

- swarm mode activates by count of work body parts
- check for sources for empty adjacent spots witch fixes #65
- in swarm mode use native moveTo to handle creeps positions

improve harvesting resources by several creeps on low stages of game

---

.jshintrc
src/config.js
src/prototype_creep.js
src/prototype_creep_harvest.js
src/prototype_roomPosition.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/role_carry.js
src/role_reserver.js
src/role_sourcer.js

- Make sizes dependant on the capacityAvailable
- Calculate carry spawn based on the size and throughput of the sourcer over time
Some fixes
- Improve carry handling, stuck on RCL 4
- Fix external room roads
- Fix reserver

Improve sourcer & carry handling

---

src/prototype_creep_fight.js

filter out rampats built on obstacle structures

fix move to rampat in fight logic

---

src/role_scout.js

Fix scout stuck on border quickly by forcing it to move into room when scout just switch room.

Fix scout stuck on border

---

src/prototype_room_wallsetter.js

Ramparts which are build because of paths shouldn't be blocked in the
costmatrix.

Fix rampart costmatrix issue

---

src/prototype_room_init.js
src/role_carry.js

- Carry doesn't dismantle links
- Add link position to costMatrix

Better link position handling

---

src/config.js
src/prototype_creep.js
src/prototype_creep_routing.js
src/prototype_room_costmatrix.js

- Improve avoiding source keepers
- Avoid trivial swamps
- Avoid sources, so carries shouldn't pickup energy from different sourcer (related to #126 and #190)

Improve room layout-costmatix

---

src/prototype_creep_startup_tasks.js
src/prototype_room_basebuilder.js
src/prototype_room_my.js
src/role_carry.js
src/role_harvester.js

Allow miss-placed hostile storage with huge amount of energy

---

doc/Manual.md
src/prototype_room_creepbuilder.js
src/require.js
src/role_signer.js

\+ pass extra properties from queue to creep's memory (this also fixes carry-helper)

new signer role for manual usage

---

src/prototype_creep_move.js

if we stay at exit position and call moveRandom, we should get out of exit position

Fix moveRandom functions

---

src/config.js
src/prototype_room_creepbuilder.js
src/role_upgrader.js

Build upgraders dependant on the `storage.store.energy`. Make sure there
is more than a configurable factor in the storage then the upgrader can
consume.

Upgrader storage dependant

---

.jshintrc
doc/Visualization.md
src/config.js
src/main.js
src/prototype_creep.js
src/prototype_creep_clean.js
src/prototype_creep_routing.js
src/role_autoattackmelee.js
src/role_defendmelee.js
src/role_scout.js
src/role_scoutnextroom.js
src/role_squadheal.js
src/visualizer.js

- add functions for visualizing costmatrix and PathFinder search results (but not called from anywhere)

Rewrite visualizer using native RoomVisual

---

src/prototype_room_creepbuilder.js

please leave a comment @TooAngel  @Nevrdid @samogot

updated docs for checkRoleToSpawn

---

src/config.js
src/prototype_creep.js
src/prototype_roomPosition.js
src/prototype_room_my.js
src/role_carry.js
src/role_harvester.js

- Improve harvester setup
- Fix harvester updateSettings
- Spawn harvester from carry dependant on energy on drop pos

Harvester handling

---

src/prototype_creep.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_costmatrix.js
src/role_carry.js

- role storage isActive check last because of performance
- TransferEnergy, check if target full
- Improve isStuck method
- Disable this.say commands
- Improve getDroppedEnergy
- Repairer blocked by wall constructionSites

Mostly energy improvements

---

src/prototype_room_creepbuilder.js

I don't know how it has worked earlier)

fix type check

---

src/prototype_room_my.js

as said in https://github.com/TooAngel/screeps/pull/354

use 2 harvester if there is 2 * energyFromStorageThreshold

---

config_local.js.example
src/config.js
src/screepsplus.js

even more public?
https://github.com/TooAngel/screeps/issues/61

improve Stats => Grafana #61

---

.jshintrc
src/prototype_room_creepbuilder.js
src/role_atkeeper.js
src/role_atkeepermelee.js
src/role_autoattackmelee.js
src/role_defender.js
src/role_defendmelee.js
src/role_defendranged.js
src/role_nextroomerattack.js
src/role_powerattacker.js
src/role_powerdefender.js
src/role_powerhealer.js
src/role_powertransporter.js
src/role_squadheal.js
src/role_squadsiege.js

I add a setting to roles, to fill up `tough` bodypart. And added to most of the attacking roles.
Because the `tough` will increase the fatigue value, so I limit the maximum to `move` amount.

Add fillTough setting to fill TOUGH bodypart

---

src/config.js
src/config_brain_memory.js
src/prototype_roomPosition.js
src/prototype_room_market.js

- If there is no sell orders for some resource, try to make one with high price
It is very useful for shard1 where market is weak
- Add balance coefficient to choose between distant room with high price and close room with low price, when selling to other's by orders

Improve market

---

src/prototype_creep_resources.js

Fix traffic jam caused by carry recycling.

Fix carry recycling

---

src/main.js

This is surely not the best solution, but currently the startup is broken as happened on #botarean

Fix fresh startup

---

src/role_carry.js

fix stuck carry

---

src/config_brain_memory.js
src/prototype_creep_startup_tasks.js

reset upgraderUpgrade without storage;
allow harvesters to rise upgraderUpgrade

upgraderUpgradeBeforeStorage

---

package.json
test-server/mods.json
test-server/package.json
utils/check_private_server.js
utils/test-private-server.sh

- Add `screepsmod-auth` to enable password authentication
- Update bot user to fixed name and spawn position
- Set user password to fixed values
- Read and print out logs via `screeps-api`

Improve test private server check

---

src/config.js
src/config_brain_memory.js
src/main.js
src/prototype_roomPosition.js
src/prototype_room_memory.js

Memory segments usage implementation 
Use segments for cost matrices

Memory segments

---

src/prototype_creep_resources.js

``this.room.controller.owner`` is an object.
> http://docs.screeps.com/api/#StructureController.owner
> **owner**
> An object with the structure’s owner info containing the following properties:
parameter | type | description
-- | -- | --
username | string | The name of the owner user.

Fix interactWithController

---

src/prototype_creep.js

This line has been printed with an incomprehensible message

Fix mySignController

---

src/config.js
src/prototype_room_my.js

just added config.room.observerRange (1 to 10) to reduce memory

added config.room.observerRange

---

.gitignore
.screepsrc.example
utils/test-private-server.sh

You can more easily connect to private server and you don't have to install screeps server globally

fix private run a bit

---

src/prototype_creep_routing.js

The PR should fix alot of recent seen strange behaviors. Please merge it and look if your fixes are still needed.

fix followPath

---

src/prototype_creep.js
src/prototype_creep_fight.js
src/prototype_creep_move.js
src/prototype_roomPosition.js
src/prototype_room_creepbuilder.js
src/role_atkeeper.js
src/role_defendmelee.js
src/role_powerattacker.js
src/role_scoutnextroom.js
src/role_sourcer.js
src/role_towerdrainer.js
src/utils.js

I started out just replacing some broken direction-reversing code with a function, then found broken direction-changing code and replaced that too, which led me to broken random direction choosing code, and I ended up just swapping out almost all the uses of Math.random() for lodash _.random(min,max)

move direction manipulation to a function, use lodash random

---

src/prototype_creep_harvest.js
src/prototype_creep_routing.js
src/role_carry.js
src/role_sourcer.js

Disclaim :
When apply for first time, alive sourcers will use a default path's terrain datas of 10 plain. The correct values will be calculated by next sourcers spawned.
It may slow down a little/alot while waiting for next sourcers as it may be better to suicide sourcers in base if you have energy for respawn them.

Correct carry's interval

---

src/main.js

There's other code around this that I want to rearrange, maybe optimize, but just having exceptions here be caught is a nice upgrade for future development/debugging efforts.
Maybe we should be printing out the call trace like the normal exception handler?

catch exceptions in the visualizer

---

src/config.js
src/logging.js
src/prototype_creep.js
src/prototype_creep_startup_tasks.js

`config.creepLog.roles` and `config.creepLog.rooms` to filter specific
roles and rooms.

Introduce creepLog, config based logging of creeps

---

src/main.js
utils/test_on_server.js

Increase server runtime to one hour and check for level and proress

Check for controller progress RCL 2

---

src/role_nextroomerattack.js
src/role_powerattacker.js

Point function call to Creep.prototype.findClosestEnemy()

Fix "creep.pos.findClosestEnemy is not a function"

---

src/role_powerhealer.js

- Moved heal function from inner scope of action to global scope

Fix creep undefined in powerhealer heal function

---

src/prototype_room_my.js

If there are no Subscription Tokens for sale the creeps will freeze.
This almost happened to me as it replaced the spawn.
Fix for #485

Fix error with property price.

---

src/config.js
src/config_brain_main.js
src/config_brain_memory.js
src/prototype_creep.js
src/prototype_creep_mineral.js
src/prototype_creep_move.js
src/prototype_room_my.js
src/prototype_room_wallsetter.js
src/role_defendranged.js
src/role_harvester.js
src/role_planer.js
src/role_repairer.js
src/role_scout.js
src/role_upgrader.js

- Document and improve functions in `prototype_creeps.js`
- Remove `stayInRoom`
- Extract methods

Refactoring `prototype_creep.js`

---

src/config.js
src/config_brain_memory.js
src/logging.js
src/prototype_creep.js
src/prototype_creep_move.js
src/prototype_creep_routing.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_init.js
src/prototype_room_wallsetter.js

`debugLog` logging can be configured via `config.debug` and simplifies
logging, debug and configuration which log should be shown.

Introduce `debugLog` for rooms

---

src/prototype_room_basebuilder.js

Fix issue, if there is no controller.

`prototype_room_basebuilder`

---

src/prototype_room_init.js

Check for `misplacedSpawn` when setting room layout

---

src/prototype_creep_resources.js

Save the current target in memory and stick to it as long as it exist.

`construct` task, stick to one target

---

src/config.js
src/config_brain_main.js

updateSkippedRoomsLog + lowExecution

---

src/prototype_creep_resources.js

Executing creep role failed: W5N0 harvester-628  Cannot read property 'ticksToDowngrade' of undefined

fixes Cannot read property 'ticksToDowngrade' in https://circleci.com/gh/TooAngel/screeps/2045

---

src/prototype_creep_move.js
src/prototype_room_costmatrix.js
src/prototype_room_init.js
utils/test_on_server.js

If the spawn is misplaced we use a custom costmatrix to simplify the
pathing of the creeps.

BaseCostmatrix for misplacedSpawn

---

src/prototype_room_creepbuilder.js

Improve debugging
Refactor `inRoom()` and check if the target is set

`prototype_room_creepbuilder`

---

src/config_brain_memory.js
src/config_brain_memory_market.js
src/config_brain_squadmanager.js
src/require.js
src/role_harvester.js

better buyPower
moved handleIncomingTransactions

some improvement part 2

---

src/prototype_creep_resources.js

Check for controller before checking values

prototype_creep_resources

---

src/prototype_room_my.js

- Use debuglog
- Restrict `!building` to the point where `sourcerer` can fully harvest
a source
- Remove weird `planer` building condition
- fix links with inactive links

`prototype_room_my`

---

src/prototype_room_my.js
src/role_carry.js

Remove old logic, carries call harvester

`role_carry` spawn harvester without target

---

src/prototype_roomPosition.js
src/prototype_room_basebuilder.js
src/prototype_room_init.js

RoomPosition constructor is now only accepting correct values. We need to ensure coordinates are valid (>=0 and < 50).
This fixes bug #554

fix issue #554 (W12N25 Error: Invalid arguments in RoomPosition)

---

.circleci/config.yml
utils/test.js

- Update milestones
- Cleanup circleci config

Small fixes

---

.circleci/config.yml
package-lock.json
package.json
src/prototype_room_basebuilder.js
src/prototype_room_my.js
src/prototype_room_utils.js

- Mostly extract methods from the complex ones
- Start to migrate away from `findPropertyFilter`
- Auto deploy to screeps server (not sure why it was not there)
- Disable grafana updates

Improve complexity

---

.eslintrc-slow
package-lock.json
package.json
src/prototype_creep.js
src/prototype_creep_mineral.js
src/prototype_creep_startup_tasks.js
src/prototype_room_basebuilder.js
src/prototype_room_controller.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/prototype_room_wallsetter.js
src/role_harvester.js
src/role_nextroomer.js
src/role_scout.js
src/role_scoutnextroom.js
src/role_storagefiller.js
src/visualizer.js

Reduce complexity to 20

---

src/prototype_room_memory.js
src/role_harvester.js
utils/grafana.js
utils/test.js
utils/testHelpers.js

- Remove duplicate code
- Fix issues in `utils/`

Improve code quality

---

.eslintrc-slow
src/prototype_creep_mineral.js
src/prototype_creep_move.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_controller.js
src/prototype_room_costmatrix.js
src/prototype_room_my.js
src/prototype_room_wallsetter.js
src/role_nextroomer.js
src/role_reserver.js
src/role_scoutnextroom.js
src/role_storagefiller.js

- Improve complexity to max 19
- Remove noise
- Fix nextroomer bug

Fixing errors are deleting room memory

---

.circleci/config.yml
Gruntfile.js
package-lock.json
package.json
src/prototype_room_my.js
utils/test.js

- Increase runtime to 200 minutes
- Update CircleCI config for longer period of no output
- Only consider milestones with tick less than last tick
Fixes #579

Improve CI testing

---

config_local.js.example
main_local.js.example
src/.gitignore
src/config.js
src/config_brain_main.js
src/config_brain_stats.js
src/main.js
src/prototype_room.js
src/prototype_room_my.js
src/role_harvester.js
src/utils.js

Added mainLocal for custom code.
mainLocal example for Pixel generation.
Always fix misplacedSpawn.
Fixed cpuStats.enabled typo.
Fixed linkStorage search function.
If room energyAverage <= 300 spawn low harvester to get everything running.

Added mainLocal and bugfixes.

---

src/config_brain_stats.js
src/prototype_room_creepbuilder.js

Removed unnecessary assignment.
@TooAngel is there a way to delay `worlddrive merge`?

Fixed codeclimate.

---

Gruntfile.js
README.md
package-lock.json
src/prototype_creep.js
src/prototype_creep_resources.js
src/prototype_room_find.js
src/prototype_room_my.js
src/prototype_room_wallsetter.js
src/require.js
test/test.js
utils/test.js

Unit test:
Read constants from the server and set it as global.
Define mock classes/prototypes for the usual objects.
Test simple harvester config.
Improve code climate:
- Remove noise of dead creeps
- Improve code quality of `prototype_room_my`, mainly be extracting
methods

Unit test and code climate

---

src/prototype_creep_fight.js
src/prototype_creep_squad.js
src/role_squadsiege.js

Fixes https://github.com/TooAngel/screeps/issues/542

Fixed siege squad, removed some useless log

---

README.md
package-lock.json
package.json
src/prototype_room_market.js

Sometimes a room can not be access, checking for that.
Update dependencies.

Market bug

---

src/prototype_room_creepbuilder.js
src/prototype_room_my.js

Extract a couple of methods and cleaned up logic of some methods.

Refactor `prototype_room_my`

---

.worlddriven.ini
README.md
src/prototype_room_creepbuilder.js

- Merge method is now squash
- No increase with multiple commits
- Decrease merge time to 7 days
- Add World Driven link to README.md
- Fix issue with too many body parts

Decrease merge time, add World Driven to README

---

Gruntfile.js
README.md
package-lock.json
package.json
src/brain_memory.js
src/brain_quests.js
src/brain_squadmanager.js
src/diplomacy.js
src/prototype_creep.js
src/prototype_room.js
src/prototype_roomPosition_structures.js
src/prototype_room_costmatrix.js
src/prototype_room_external.js
src/prototype_room_memory.js
src/prototype_room_routing.js
src/role_nextroomer.js
src/role_quester.js
src/role_storagefiller.js
src/role_upgrader.js
src/visualizer.js

The public TooAngel account was wiped by other players, `_GrimReaper`
was so nice to build up a spawn again. As the reputation system does not
cover this yet, this commit will try to give at least something back.
Also
- Only `myRooms` should use `memory`.
- Small quest fixes
- Uninitialized object or array fixes
- Automated deploy only for the public world

Thank _GrimReaper

---

src/prototype_creep_resources.js

close https://github.com/TooAngel/screeps/issues/666

[LOGIC REFINE]add withdrawRuin

---

src/prototype_room_creepbuilder.js
src/utils.js
src/utils_creep_part.js
test/test.js

close https://github.com/TooAngel/screeps/issues/672
now the creeps can take more demage before they totally cannot work as its role.

[CREEP REFINE] re-order creep's body part position.

---

src/prototype_creep_fight.js
src/role_squadsiege.js

now it will not try to dismental controller anymore.
besides `this.pos.findClosestByPath(FIND_HOSTILE_STRUCTURES, STRUCTURE_TOWER);` will actually search for any structure, with wrong use of `opt` param, so fix it.

[BUG]fix bug in construction target finding in role squadsiege.

---

src/config.js
src/prototype_room_basebuilder.js
src/prototype_room_init.js

failure of XenoAmess, from https://screeps.com/a/#!/history/shard1/E49S27?t=42643500 to https://screeps.com/a/#!/history/shard1/E49S27?t=42645100 , shows it is really dangerous to destroy StructureSpawn when you have too few destroyStructureSpawn, so please only do it when you have another 2, at least you will not die like what XenoAmess suffered.

[LOGIC REFINE]only do destroyStructureSpawn after you have at least several Spawns now.

---

doc/CodeBase.md
package.json

Mostly increasing the version so that it will be released.

Improve setup documentation and increase version

---

src/brain_main.js
src/brain_memory.js
src/brain_nextroom.js
src/main.js
src/role_autoattackmelee.js
src/role_nextroomerattack.js

Changing methods from binding them to the global `brain` object to standard functions and exports / require the ones which are used in other modules. This makes it easier to understand where which function is used.

Refactor brain

---

src/prototype_room_creepbuilder.js

close https://github.com/TooAngel/screeps/issues/674

[WIP][LOGIC REFINE] allow spawn creep to other than top

---

src/role_autoattackmelee.js

bugfix: bugfix for autoattackmelee in a room without controller, and try to attack STRUCTURE_KEEPER_LAIR

---

src/prototype_creep_resources.js
src/prototype_room_basebuilder.js
src/role_sourcer.js

refine: refine sourcer pickup energy logic. Also allow build container in base, when have no link nearby.

---

package.json
src/brain_main.js
src/brain_squadmanager.js
src/prototype_creep_fight.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition_find.js
src/prototype_room_find.js
src/prototype_room_my.js
src/require.js
src/role_nextroomer.js

Another round of cleaning up code.
Converted some more function in brain to actual functions. Improved some methods with high max-statements.

More brain refactoring and reducing max-statements

---

.gitignore
doc/CodeBase.md
package-lock.json
package.json
src/brain_main.js
src/brain_stats.js
src/main.js
src/prototype_creep_routing.js
src/prototype_room_creepbuilder.js
src/prototype_room_market.js
src/prototype_room_my.js
src/prototype_room_routing.js
src/prototype_room_utils.js
src/utils.js

The `src/utils.js` module should provide function to the user, to be used via the console.

Cleanup the user utils

---

src/config.js

Disable commodities and attack log by default.

reduce noise

---

package-lock.json
src/main.js

- Add try/catch blocks around main logic and post-tick operations to prevent crashes
- Extract functions for better readability: runMainLogic(), runPostTickOperations(), updateResourceStats()
- Replace magic number 2000000 with named constant MEMORY_LIMIT
- Add comprehensive JSDoc documentation
- Improve error logging with tick context and stack traces
- Ensure stats and pixel generation continue even if main logic fails
This improves bot resilience and maintainability for the Screeps automation.

Refactor main.js: Add error handling and improve code organization

---

package-lock.json
package.json
src/config.js
src/prototype_creep.js
src/prototype_roomPosition.js
src/role_sourcer.js

- Update screeps-api from 1.16.0 to 1.16.1 (security fixes)
- Remove unused config properties (helpThreshold, needThreshold, pathFindIncomplete)
- Optimize array length checks for better performance:
- Replace .length === 0 with !length
- Replace .length > 0 with !!length
- Fix version specification to remove ^ for exact versioning
All changes are backwards compatible and tests pass.

Update dependencies and optimize code

---

README.md
doc/Diplomacy.md
doc/Manual.md
doc/Mineral.md
doc/Testing.md
doc/Visualization.md
package.json
src/prototype_creep_startup_tasks.js

This PR comprehensively improves both the code structure and documentation across the Screeps bot codebase, focusing on the startup task system and general documentation clarity.
- **Enhanced Documentation**: Added comprehensive file header explaining the startup task system architecture and usage patterns
- **Better Organization**: Restructured file into clear sections with proper separation of concerns
- **Named Constants**: Extracted magic numbers into well-named constants for better maintainability  
- **Consistent JSDoc**: Added comprehensive documentation for all public methods with parameters and return values
- **Refactored Methods**: 
- Split `upgradeControllerTask` to extract energy pickup logic
- Improved `buildRoads` with focused helper functions
- Broke down large …

refactor: improve startup tasks code structure and documentation
