TooAngel/screeps

src/main.js

Will skip a tick instead of using all the cpu then erroring.
Eventually it will save up enough cpu to run a tick, then become stable in only running once every several ticks, instead of erroring every single tick.

Skip tick if not enough cpu

---

src/config.js
src/prototype_room_creepbuilder.js
src/role_carry.js

Spawn 'reserver' after 'carry' and 'sourcer' to constantly have the
external supply lines running.
Change carryPercentage for less jumping around at one spot.
Testing on live

Add external supply to queue

---

src/config.js
src/main.js
src/prototype_creep_resources.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/prototype_room_utils.js

A must have :)
Calculate energyAvailable along congifuredpediode then set them as helper or neddHelp. Then, each 100 ticks end, if a room have a too hight energy average, she will spawn a carry for send energy to nearest one which need it.
If a needHelp room have hostile creeps, a terminal or no spawn in or if she doesn't need more help, she is removed from list.

Manage lowenergy rooms

---

src/prototype_creep_mineral.js

Monitor reaction product lab for target amount of minerals.
At target amount, pull minerals out of terminal.

Creep Mineral Hotfix

---

src/role_nextroomer.js

Not sure why execute gets called, but this fixes them getting stuck after execute and eop message.

Remove moveTo(25,25) in nextroomer execute

---

src/prototype_room_costmatrix.js

The execution scope was not a room => line 50 was throwing undefined is not a function for findPropertyFiltre

Fix: Invalid scoping inside a callback in costmat

---

src/prototype_creep.js
src/prototype_creep_fight.js
src/prototype_creep_mineral.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_creep_startup_tasks.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_defense.js
src/prototype_room_external.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/prototype_room_wallsetter.js
src/role_nextroomer.js
src/role_powerattacker.js
src/role_powerdefender.js
src/role_powerhealer.js
src/role_powertransporter.js

When without was false and table[s[property]] was false it was always returning true, instead of the intended false.

Fix: Invalid findPropertyFiltre filter

---

src/role_carry.js

Helper creeps get stuck and cause traffic jam if the storage they are wanting
to fetch energy from is empty. So suicide them.

Fix stuck carries

---

src/prototype_room_creepbuilder.js

These are the changes I needed to make to keep creeps spawning with the lastest code release of TooAngel.
this.memory.roles[WHATEVER_ROLE] never got set back to false so no more creeps of that role would be spawned.
Fixes #245

Keep spawns working

---

src/prototype_creep.js
src/prototype_room_costmatrix.js

Sometimes creeps that should stay in room stacks on border, moving out of room and in next tick again into room, due to stayInRoom method. Most common case is repairers
The reason is due to avoidBorder, moving to target inside room costs more than move on plain terrarian (without cost matrix on adjacent room without visibility)
The fix is disallow moving into other room if source and target a both in one room.

Fix repairers and sometimes other creeps stack on border

---

src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js

Improve logic on sourcer overflow. Instead of waiting for dropped energy on each tick, until creep get full, withdraw than energy from sourcer/container, to get full in two ticks and free up capacity for sourcer to avoid overflowing

Improve logic on sourcer overflow. 

---

.eslintrc
src/config.js
src/config_brain_memory.js
src/prototype_creep.js
src/prototype_creep_mineral.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_creepbuilder.js
src/prototype_room_init.js
src/role_carry.js
src/role_harvester.js
src/role_nextroomer.js

- Extract findCreepWhichCanTransfer
- Extract sayIdiotList
- Reduce complexity for buildContainer
- Improve `transferToCreep`
- Extract `filterTransferrables`
- Delete `transferMy`
- Remove \'aa\'
- Extract getEnergyFromSource
- Improve `construct`
- Not Build road < RCL 4
- Delete nextroomer from memory if they died
- Fix harvester bug, Recover: no creep, < 400 energy available
- Fix layout issue, where powerspawn and filler area tower are not set in the costmatrix
- Improve getEnergyFromSource
- Small creep_resource refactoring
- Extract `checkEnergyTransfer`
- Refactor `filterTransferrables`
- Extract `transferAllResources`
- Refactor `getEnergyFromSource`
- Extract `setHasEnergy`
- Extract `clearPosition`
- Extract `getTransferTarget`
- Refactor `handleReserver`
- transferEnergyMy: …

Refactor `prototype_creep_resources`

---

src/config.js
src/prototype_creep_resources.js

- extract highway rooms value into config
- fix infinite loop between base and highway rooms if cary percentage between 0.1 and 0.2

Improve carry percentage config

---

src/prototype_creep.js

Oops... My last change broke building any roads on swamps instead of forcing it building in low RCL rooms. Now it's fixed

Fix build road on swamps

---

src/role_carry.js

Sometimes carrys is queue too long, causing the path to be blocked elsewhere.

Give way when carry is stuck

---

.eslintrc
circle.yml
grafana/main/db/combined-rooms-datas.json
grafana/main/db/last-24h-tables.json
grafana/main/db/players-comparaison.json
grafana/main/db/rooms-summary.json
package.json
utils/grafana.js

Including the grafana dashboards in the repository. On deploy
the dashboards are checked and deployed if the version is newer.
If the online version is newer an exception is thrown.
This enables every contributor to suggest and deploy changes to
the dashboard configuration.

Auto deploy grafana dashboards

---

src/role_harvester.js

TooAngel gave me the extra check in the role_harvester after we saw my room die after building its storage at RCL 4. It seems to have gotten my room back online.

fixed harvesters in rooms with misplaced spawns

---

src/config.js
src/prototype_creep_harvest.js

Carries is spawned faster then they can move to sourcer to change dropped resource amount

Fix carry spawn rate for low RCL

---

src/prototype_roomPosition.js
src/prototype_room_init.js

we have a such chain:
```
controller - upgrader - storage - pathStart
                               \- filler
```
where each next position was first valid adjacent position
in this cange instead of first valid position, "best" valid position will be taken, where "best" is position, which have the biggest number of valid positions adjacent to it
- By taking best position instead of first for upgrader, we reserve some space for potentially several -
upgraders
- By taking best position instead of first for storage, we increase chances that we will have enough positions for pathStart, roads and filer
- For pathStart, first position is enough

Fix layouts with no filler position

---

src/prototype_room_memory.js

Global variables are tied to server node. Due jumping between nodes, it is hard to invalidate global cache from console without reruning code. Simple clearing cache from console may cause errors and even incorrect layout.

Safe way to invalidate room memory

---

src/config.js
src/prototype_creep_mineral.js
src/prototype_room_mineral.js
src/role_extractor.js

- send more resources (bought and intermediate reagents) between rooms
- fix terminal overflowed with energy
- config option for debug logging
- stop reaction if no more resources left
- early suicide mineral creep to not waste dropped minerals
- count all tiers of reaction to check if we reach the limit

Improve mineral handling

---

src/prototype_creep_mineral.js
src/role_planer.js

Roads are mainly build due to `harverster` and `carry` creeps, no need to execute it in planer.
Catch exception for mineral creep.

screeps.com fixes

---

src/role_carry.js

Updated the `roles.carry.handleMisplacedSpawn` to skip the better position.
Placing an initial spawn in an initially not optimal spot causes traffic jams and issues. This will temporarily skip the code which delays re-positioning the room.

Add break out of conditional for misplaced spawn

---

src/config.js
src/prototype_creep_fight.js
src/prototype_creep_squad.js
src/prototype_room_attack.js
src/require.js
src/role_autoattackmelee.js
src/role_scout.js
src/role_squadheal.js
src/role_squadsiege.js

- Defend reserved rooms
- Autotrigger all attacks: autoattack, squad.start and attack42
Fixes #35

Improve fighting

---

src/prototype_creep_resources.js
src/role_carry.js

Carry will drop resources at `pathStart` if storage is full
Updated:
Fixed `transferToStructures`

Fixed carry stuck at `pathStart` when storage is full

---

src/role_carry.js

```
1963970 W46S8  carry-6969           [room W46S8 pos 6,21] Executing creep role failed: W46S8 carry-6969 59c5ee1d246307774f52dc01 {"x":6,"y":21,"roomName":"W46S8"} TypeError: Cannot read property 'x' of undefined
TypeError: Cannot read property 'x' of undefined
at Object.roles.carry.handleMisplacedSpawn (role_carry:87:50)
```
This might not be the best fix, but it handles null and undefined instead of just null.

check source for truthiness, not just !== null

---

src/role_scoutnextroom.js

this looks like a simple typo? memory.target is a RoomPosition, I think. probably just meant to say the goalRoom set when the target is set.

scoutnextroom will say their goalRoom instead of undefined

---

src/prototype_room_external.js

```
[12:50:23 PM][shard1]1950483 W49S10                      Executing room failed: W49S10 TypeError: Cannot set property 'W49S10' of undefined TypeError: Cannot set property 'W49S10' of undefined
at Room.externalHandleHighwayRoom (prototype_room_external:116:34)
```
error occurs if the first powerbank you see is almost decayed

fix nonexistent Memory.powerBanks sooner

---

src/visualizer.js

This changes the yellow text visualization to the first letter of the creep's target, rather than a number that's almost always '5'.

Better creep position visualization, letters instead of numbers

---

src/prototype_creep.js

A creep with low MOVE or walking through swamp isn't stuck just because it's been sitting still for three ticks. It's stuck if it's sitting still for three ticks after its fatigue reaches zero.

only update memory.last when fatigue === 0

---

src/prototype_room_defense.js

sparr [Sep 24th at 9:00 AM] 
in #angels_public
why is the default here true instead of false? do we really want a notification when an unrecognized scout enters our room?
1 reply
tooangel [3 days ago] 
Yes, surely should be false. Also the notification are not necessary

don't consider move-only creeps attackers

---

src/prototype_room_init.js
src/prototype_room_memory.js
src/visualizer.js

Currently the room.memory.summaryCenter has to be set manually. I plan to add a function to room.updatePosition() that keeps track of the emptiest part of the room, then moves the summary there.

move visuals summary to dynamic location

---

src/main.js

ScreepsPl.us has a Game.cpu.tickLimit of 10100 for some weird reason

don't skip ticks if tickLimit is unusually high (private servers?)

---

src/prototype_creep_mineral.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_init.js
src/prototype_room_market.js
src/prototype_room_memory.js
src/prototype_room_mineral.js
src/role_storagefiller.js

improve performance of RoomPosition.inPath
fix planer build roads task
swap lab and terminal construct priorities
refactor out costMatrixSetSourcePath
- refactor setFillerArea
- move terminal near to fillerPos
- change labs layout to improve reaction perfomance (two fixed source labs, all other - result labs)
- move labs as near to pathStart as possible (on any path)
improve resource balansing between storage and terminal
- delete such code from mineral creep
- implement new one in storage filler
- smarter balancing of minerals
Add labs position
Refactor reaction result amount
No layout version bump - waiting for sparr's #457
TODO:
- improve lab reaction handling logic to use new layout (several result labs)
- improve mineral creep logic - split into to creeps: miner and carry

Mineral handling improvement

---

src/prototype_roomPosition.js
src/prototype_room_init.js

Currently attempting to re-place creep positions in a room is not idempotent because they will avoid the paths previously planned to reach them. This patch introduces a way to pass options down through the relevant calls so that validPosition can be told to ignore specific position features.

add options to validPosition(), ignore paths when placing sourcers

---

src/prototype_room_my.js

Got stuck in e.g. E21N8, two harvester for switching at the storage,
only filling two extensions, blocking the path for other creeps.

Make two harvester RCL > 6 dependent on the energyAvailable

---

src/config.js
src/config_brain_nextroom.js

Introduce `config.nextRoom.cpuPerRoom` to be able to set min CPU
per room and avoid claiming of new rooms.

Restrict new room claiming on `cpu.limit`

---

src/prototype_creep.js
src/prototype_creep_clean.js
src/prototype_creep_fight.js
src/prototype_creep_harvest.js
src/prototype_creep_mineral.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_room_basebuilder.js
src/prototype_room_costmatrix.js
src/prototype_room_creepbuilder.js
src/prototype_room_defense.js
src/prototype_room_external.js
src/prototype_room_mineral.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/role_atkeeper.js
src/role_atkeepermelee.js
src/role_autoattackmelee.js
src/role_nextroomer.js
src/role_storagefiller.js
src/role_structurer.js

- Add one more level of caching. CPU usage reduced by half
- Add option to use outdated finds for not critical tasks (for example may be used to reduce rate of structures searches, as they are changed rarely). This option is unused for now
- Move `without` parameter as one of `opts` properties and refactor usages

Rewrite findPropertyFilter

---

src/role_nextroomer.js

In the past the `ticksToDowngrade` were resetted as soon as an upgrade
on the controller happen. Now it is only incremented.
Nextroomer logic is now, to upgrade controller if < 0.1
`ticksToDowngrade`, or if close to the controller.

Upgrade controller to full `ticksToDowngrade`

---

src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/role_carry.js
src/role_nextroomer.js

fixes some routing and direction problems with carry and soucer

some improvement part 3

---

src/config.js
src/prototype_creep_resources.js
src/prototype_creep_routing.js
src/prototype_creep_startup_tasks.js
src/prototype_room_market.js
src/prototype_room_my.js
src/prototype_room_utils.js
src/role_storagefiller.js

added pickupEnergy in getEnergy
better sellByOthersOrders
fixed canHelpRooms + needEnergyRooms
fixed energy and power transfer of role_storagefiller

some improvement part 4

---

package-lock.json
package.json

So you can make use of all the shiny new features without eslint complaining.

Upgrade eslint-plugin-screeps

---

src/config_brain_stats.js
src/prototype_creep_resources.js
src/prototype_room_creepbuilder.js
src/prototype_room_my.js
src/role_harvester.js

Fixed creep builder updateSettings function. (lodash merge)
Harvester prefers empty spawns and extensions before anything else.
Added logging to config.debug.spawn.
Cleared unnecessary stuff from harvester.updateSettings.
Fixes #585

Fixes harvester bug for high gcl and energy <= 350

---

package.json
src/config.js
src/prototype_room_init.js

The link with is next to filler needs to be the first in the position
list. Especially the link transfer logic relies on that fact.
Update bot version so that a new version is released for the private
server.
!! Updating the room layout version, this will recalculate the rooms and
might lead to a room rebuild. The only intended change is the position
of the storage link in `memory.position.structure.link`.
Fixes #582

Fix storage filler link position

---

src/prototype_room_creepbuilder.js

The harvester spawns without `targetId` but it is set in the later
process. When comparing creeps it needs to check for the 'wildcard'
`targetId` to match harvesters.

Fix only spawn harvester bug

---

src/config.js
src/prototype_room_creepbuilder.js
src/prototype_room_external.js
src/prototype_room_keeper.js
test/test.js
utils/testConfig.js

- Handle center rooms, Fixes #616
- Disable watchers, don't' know what they are good for
- Reduce complexity in prototype_room_creepbuild by extracting methods
- Decreasing observer range to reduce memory (this is just a workaround)

Small fixes to reduce noise

---

src/prototype_room_creepbuilder.js
src/prototype_room_my.js

Have been playing with this bot for the last few days and noticed/fixed a couple bugs that popped up. 
- The creepbuilder was frequently returning `spawnCreateCreep body too long` because the `getPartConfigMaxBodyLength` was not properly being passed the prefix and suffix strings
- Nextroomers were not being called, nor rooms revived because `reviveMyNowHelperValid` previously never returned true, meaning the following code block would always execute and it never got to the `helperRoom.checkRoleToSpawn('nextroomer', ...)` line
```
if (!this.reviveMyNowHelperValid(helperRoom)) {
continue;
}
```

Bugfix nextroomers not being called and creep builder

---

doc/API.md
doc/BaseBuilding.md
docker-compose-setup.yml
docker-compose.yml
package-lock.json
package.json
src/brain_nextroom.js
src/config.js
src/diplomacy.js
src/logging.js
src/prototype_creep.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_room_external.js
src/quests.js
src/role_builder.js
src/role_carry.js
src/role_mineral.js
src/role_quester.js
src/role_reserver.js
utils/testConfig.js

- Improve and fix reservation logic. Intended reservered rooms were
flagged as unreservered
- Reduce code complexity
- New carrys more first to the target before accepting transfers. E.g.
commodity carry are integrated into the carry network and reached the
target to late
- Fix getEnergyFromStorage, especially on `misplacedSpawn`
- Adapt code to the quest logic from the documentation

Reservation, carry, getEnergyFromStorage

---

src/prototype_creep_startup_tasks.js

@TooAngel I cannot say there be 0 possibility that it be a bug, but I really think it possibly be a hacking-attack to this repo. 
please review as soon as possible, thanks. 
wow when room have a storage and room is not misplacedSpawn, it will call a non-exist function, cause error, thus all creeps just brain-down and cannot extract any energy. 
REALLY NICE HACKING FOR KILLING ROOM-LEVEL4+ PLAYERS, INCLUDING ME THIS AFTERNOON TODAY.

[SEVERE]Fix getEnergyFromStorage code changed by wilken which cause if room have a storage, all creeps brain-down, and you lose the battle soon.

---

src/brain_nextroom.js

which will cause if config.nextRoom.resourceStats = true, everything boomed up.

[SEVERE]fix bug about misuse global.stats and global.data.stats

---

src/diplomacy.js

fix a debug log who would cause error like:
Error: Could not find an object with ID 63174ac39538317abc9be996
at data (:51004:15)
at Object.get [as name] (eval at exports.defineGameObjectProperties (:586:9), :7:60)
at Object.exports.defineGameObjectProperties.obj.toJSON (:610:29)
at JSON.stringify ()
at findRoomPairs (diplomacy:53:73)
at handleRetaliation (diplomacy:121:20)
at addToReputation (diplomacy:167:7)
at Object.Room.handleReputation (prototype_room_my:344:7)
at Object.Room.executeRoomHandleHostiles (prototype_room_my:488:8)
at Object.Room.executeRoom (prototype_room_my:508:8)

[BUG]fix a debug log who would cause error

---

src/prototype_room_external.js

The creeps shouldn't consider the room with tower blocked as long as its owner is oneself. This could be useful in following situation:
Room A | Room B | Room C
If you have room C as your base room, and you claimed room B, built a tower in room B.  
And at some time you want room A, but you only get 2 GCL, then room B must be unclaimed.  
If you forget to destroy the tower in room B, the bot will maybe never reach room A (without my changes, if no other routes)!
Then consider the tower's owner. Even if a room is not owned by the user, the tower could be harmless.

Consider the room with a tower not blocked if it was unclaimed by oneself

---

package-lock.json
src/prototype_room_creepbuilder.js

According to https://docs.screeps.com/start-areas.html
> The sector is completely separated from the outer world with a blind, indestructible wall preventing outside players from entering it. Getting inside a Novice Area is possible only by placing there your initial spawn directly.
It's impossible to travel between rooms with different status, so sending reservers is just wasting energy.  
Now check before sending them.
Updated Nov 6, 2022:
In a reserved room in a novice area, and next to normal area, walls exist but cannot be destroyed. Reservers shouldn't call structurers if the structure is not able to be destroyed.

[LOGIC REFINE]prevent sending useless reservers

---

src/prototype_room_creepbuilder.js
utils/testConfig.js

- The spawn direction can only by TOP right now, as the room layout is designed that way.
- When starting the private server `getRoomStatus` is not directly available => Catching the exception
- `base` is not always provided when spawning a creep, using the room name in that case.

Fixing last merged issues

---

package-lock.json
package.json
src/prototype_creep_clean.js
src/prototype_creep_fight.js
src/prototype_creep_heal.js
src/prototype_creep_resources.js
src/prototype_creep_startup_tasks.js
src/prototype_roomPosition.js
src/prototype_roomPosition_find.js
src/prototype_room_defense.js
src/role_atkeeper.js
src/role_autoattackmelee.js
src/role_mineral.js
src/role_nextroomer.js
src/role_nextroomerattack.js
src/role_powerhealer.js
src/role_powertransporter.js
src/role_structurer.js

Instead of abstracting the screeps API, we should extract as named functions which can be reused.
This allows to easier read the code and also allows to reused certain functions, as well as changes these at a common place in case of updates.
This is step one for removing all propertyfilter methods.

Refactor: Remove findClosestByRangePropertyFilter

---

src/config.js
src/logging.js
src/prototype_room_external.js
src/prototype_room_my.js

Store for each of `myRooms` the time a spawn is idle. Include this in the reserver logic and restrict new reservation on a spawnIdle threshold.
Currently too many rooms are tried to be reservered, while the actual `reserver` creeps are queue due to busy spawns.
The `spawnIdle` check tackles this issue.

Introduce `spawnIdle`

---

src/config.js
src/prototype_room_my.js
src/role_upgrader.js
test/test.js

Implements dynamic upgrader scaling for RCL 8 rooms based on storage energy levels to prevent resource starvation.
- Modified `roles.upgrader.updateSettings()` to use linear scaling at RCL 8
- Storage levels now control upgrader work parts:
- ≤10k energy: 1 WORK part (1 energy/tick)
- ≥800k energy: 15 WORK parts (15 energy/tick, max)
- Linear interpolation between thresholds
- RCL < 8 maintains existing formula for backward compatibility
At RCL 8 with low storage (10k), the previous formula allocated 3 WORK parts, consuming too much energy when resources were already scarce. This change reduces consumption when storage is low, allowing the economy to recover, while maintaining full upgrade speed when resources are plentiful.
- Verified linting passes
- Tested formula outputs at various …

feat: add dynamic upgrader scaling for RCL 8
